name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_vet_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '>=1.18 <2']
    steps:
    - uses: actions/checkout@v3

    - name: Go ${{ matrix.go }} 
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }} 

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...
